---
- name: Update APT cache and upgrade packages
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600

- name: Install Unattended Upgrades
  apt:
    name: unattended-upgrades
    state: present

- name: Configure Unattended Upgrades
  copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
    owner: root
    group: root
    mode: '0644'

- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: Start and enable fail2ban
  systemd:
    name: fail2ban
    enabled: yes
    state: started

- name: Disable root SSH login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
  notify: Restart SSH
